config_cls: MossTTSPipelineConfig
model_path: OpenMOSS-Team/MOSS-TTS-v1.5

stages:
  preprocessing:
    model:
      device: cpu
      dtype: float32
    scheduler:
      max_concurrency: 1

  tts_engine:
    engine:
      max_running_requests: 1
      max_total_tokens: 8192
      mem_fraction_static: 0.78
      cuda_graph_max_bs: 1

  vocoder:
    model:
      dtype: bfloat16
    scheduler:
      max_batch_size: 1
      max_batch_wait_ms: 2
